version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.4.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: build project
          command: npm run build
