name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.3.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/nurul/htdocs/nurulislam.dev
            git pull origin main
            npm install
            npm run build
